name: GitHub Actions

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd client
      - name: install modules and build project.
        run: |
          cd ./client
          npm install
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: project-build
          path: ./client/build
  deploy:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: project-build
          path: ./client/build
      - run: ls
      - run: 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
      - name: Set up SSH private key.
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
      - name: Delete build folder in server if it exists.
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf /var/www/voiceofossetia.ru/build"
      - name: Adding build to server via SSH.
        run:  scp -r ./client/build ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/voiceofossetia.ru
      - run: echo "Deploy finished."