name: GitHub Actions

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  SERVER_URL: https://api.voiceofossetia.ru
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}

#on:
#  push:
#    branches: [ master ]

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules and build for frontend.
        run: |
          cd ./client
          echo "REACT_APP_SERVER_URL=$SERVER_URL" > .env
          npm install
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: project-build
          path: ./client/build
  deploy-client:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: project-build
          path: ./client/build
      - run: 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
      - name: Set up SSH private key.
        run: eval "$(ssh-agent -s)"
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - run: ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      - run: ssh-add - <<< "${{ secrets.SSH_KEY }}"
      - name: Deleting frontend build files and adding new ones.
        run: | 
          ssh $SSH_USER@$SSH_HOST "rm -rf /var/www/voiceofossetia.ru/*"
          scp -r ./client/build/* $SSH_USER@$SSH_HOST:/var/www/voiceofossetia.ru
      - name: Pulling repository.
        run: |
          ssh $SSH_USER@$SSH_HOST "cd /var/www/api.voiceofossetia.ru && git pull"
      - name: Deleting welcome page files and adding new ones.
        run: |
          ssh $SSH_USER@$SSH_HOST "rm -rf /var/www/welcome.voiceofossetia.ru/*"
          scp -r ./welcome/* $SSH_USER@$SSH_HOST:/var/www/welcome.voiceofossetia.ru
      - name: Setting up backend.
        run: ssh $SSH_USER@$SSH_HOST "cd /var/www/api.voiceofossetia.ru/server && su azamat -c \" composer install --ignore-platform-reqs &&
                                                                                           composer dump-autoload -o\""
      - run: echo "Deploy finished."

